//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OKA3_PQT1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_HOADON
    {
        public int MaCTHD { get; set; }
        public int SoLuong { get; set; }
        public int MaHH { get; set; }
        public int MaHD { get; set; }
    
        public virtual HOADON HOADON { get; set; }
        public virtual HANG HANG { get; set; }
    }
}
