//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OKA3_PQT1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class CT_PHIEUQUATANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CT_PHIEUQUATANG()
        {
            this.PHIEUQUATANGs = new HashSet<PHIEUQUATANG>();
        }
        [Display(Name = "Detail code")]
        [Required(ErrorMessage = "Invalid Detail")]
        public int MaCTPhieu { get; set; }
        [Display(Name = "Quantity")]
        [Required(ErrorMessage = "Invalid Quantity")]
        public int SoLuong { get; set; }
        [Display(Name = "Date create")]
        [Required(ErrorMessage = "Invalid Date create")]
        public System.DateTime NgayNhan { get; set; }
        [Display(Name = "Date expired")]
        [Required(ErrorMessage = "Invalid Date expired")]
        public System.DateTime NgayHetHan { get; set; }

        [Display(Name = "Status")]
        [Required(ErrorMessage = "Invalid Status")]
        public bool TrangThai { get; set; }
        [Display(Name = "Discount")]
        [Required(ErrorMessage = "Invalid Discount")]
        public double GiamGia { get; set; }
        [Display(Name = "Redeem points")]
        [Required(ErrorMessage = "Invalid Redeem points")]
        public int DiemThuongDoi { get; set; }
        [NotMapped]
        public int SoLuongDoi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUQUATANG> PHIEUQUATANGs { get; set; }
    }
}
