//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OKA3_PQT1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class HANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HANG()
        {
            this.CT_HOADON = new HashSet<CT_HOADON>();
            Hinh = "~/Images/product.png";
        }
    
        public int MaHH { get; set; }
        [Display(Name = "Product name")]
        [Required(ErrorMessage = "Product name can not be blank")]
        public string TenHH { get; set; }
        [Display(Name = "Quantity")]
        [Required(ErrorMessage = "Invalid quantity")]
        public int SoLuong { get; set; }
        [NotMapped]
        public int SoLuongMua { get; set; }

        [Display(Name = "Price")]
        [Required(ErrorMessage = "Invalid price")]
        public double Gia { get; set; }

        [Display(Name = "Status")]
        public bool TrangThai { get; set; }
        public string MaLoai { get; set; }

        [Display(Name = "Description")]
        [Required(ErrorMessage = "Invalid description")]
        public string MoTa { get; set; }

        [Display(Name = "Picture")]
        public string Hinh { get; set; }
        public int MaDT { get; set; }
        public int MaSize { get; set; }
        [NotMapped]
        public HttpPostedFileBase UploadImage { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_HOADON> CT_HOADON { get; set; }
        public virtual DIEMTHUONG DIEMTHUONG { get; set; }
        public virtual LOAI LOAI { get; set; }
        public virtual SIZE SIZE { get; set; }
    }
}
